export const skillsData =[
    {
        label:"FRONT END",
        data:[
            {
                skillName:"HTML",
                percentage:"90",
            },
            {
                skillName:"CSS",
                percentage:"60",
            },
            {
                skillName:"JAVASCRIPT",
                percentage:"80",
            },
        ],
    },
    {
        label:"BACK END",
        data:[
            {
                skillName:"JAVA",
                percentage:"90",
            },
            {
                skillName:"PYTHON",
                percentage:"60",
            },
            {
                skillName:"C",
                percentage:"80",
            },
        ],
    },
    {
        label:"DATA BASE",
        data:[
            {
                skillName:"MYSQL",
                percentage:"90",
            },
            {
                skillName:"MONGODB",
                percentage:"60",
            },
            {
                skillName:"ORACLE",
                percentage:"80",
            },
        ],
    }
]
